name: mllccsundayclass
description: "A new Flutter project."

#publish_to: 'none' # Remove this lineages. if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.2.1
  firebase_storage: ^12.3.0
  cloud_firestore: ^5.4.1
  flutter_animate: ^4.0.2
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.1
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.4.1
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  intl: ^0.19.0
  firebase_database: ^11.1.2
  youtube_player_flutter: ^8.1.0
  onesignal_flutter: ^3.5.0
  http: ^1.2.2
  flutter_riverpod: ^2.5.1

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash_logo.png
