// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkSmSxTC_KzWtyDVEUTIY_bF3fPm4LWzc',
    appId: '1:707858277312:web:284940c68b620450c55e25',
    messagingSenderId: '707858277312',
    projectId: 'mlccsundayclass',
    authDomain: 'mlccsundayclass.firebaseapp.com',
    databaseURL: 'https://mlccsundayclass-default-rtdb.firebaseio.com',
    storageBucket: 'mlccsundayclass.appspot.com',
    measurementId: 'G-20DBP3GB67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR7aKvi_pGsh1ZAS7Fo8Wg1SppWuehz_M',
    appId: '1:707858277312:android:e05af409c03d5bd6c55e25',
    messagingSenderId: '707858277312',
    projectId: 'mlccsundayclass',
    databaseURL: 'https://mlccsundayclass-default-rtdb.firebaseio.com',
    storageBucket: 'mlccsundayclass.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgtkmsf7iUF_H_S6QxBUyYmWObarH6YKY',
    appId: '1:707858277312:ios:0c559c153dd331aac55e25',
    messagingSenderId: '707858277312',
    projectId: 'mlccsundayclass',
    databaseURL: 'https://mlccsundayclass-default-rtdb.firebaseio.com',
    storageBucket: 'mlccsundayclass.appspot.com',
    iosBundleId: 'com.example.mllccsundayclass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgtkmsf7iUF_H_S6QxBUyYmWObarH6YKY',
    appId: '1:707858277312:ios:0c559c153dd331aac55e25',
    messagingSenderId: '707858277312',
    projectId: 'mlccsundayclass',
    databaseURL: 'https://mlccsundayclass-default-rtdb.firebaseio.com',
    storageBucket: 'mlccsundayclass.appspot.com',
    iosBundleId: 'com.example.mllccsundayclass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkSmSxTC_KzWtyDVEUTIY_bF3fPm4LWzc',
    appId: '1:707858277312:web:3cf4bef4c4321e27c55e25',
    messagingSenderId: '707858277312',
    projectId: 'mlccsundayclass',
    authDomain: 'mlccsundayclass.firebaseapp.com',
    databaseURL: 'https://mlccsundayclass-default-rtdb.firebaseio.com',
    storageBucket: 'mlccsundayclass.appspot.com',
    measurementId: 'G-KEH5C3X705',
  );

}